version: '3.7'
services:
  postgres-server:    # The Postgres Database Service
    image: postgres:latest
    restart: always
    environment:   # Username, password and database name variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata #data storage
    volumes:  # Volume for Database
      - zabbix_pgdata:/var/lib/postgresql/data/
  pgbackups:
    image: prodrigestivill/postgres-backup-local:11
    restart: always
    volumes:
      - "${BACKUPS_DIR:-.}/backups:/backups"
    depends_on:
      - postgres-server
    environment:
      - POSTGRES_HOST=postgres-server
      - POSTGRES_DB=${POSTGRES_DB:-zabbix}
      - POSTGRES_USER=${DB_USERNAME:-zabbix}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-zabbix}
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=80

  zabbix-server:     # The main Zabbix Server Software Service
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    restart: always
    environment:   # The Postgres database value variable
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text #Zabbix configuration variables
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
    depends_on:
      - postgres-server
    volumes:  # Volumes for scripts and related files you can add
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
  
  zabbix-web:    # The main Zabbix web UI or interface 
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    restart: always
    environment:  # Postgre database variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server  # Zabbix related and Php variables
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "America/Argentina/Cordoba"  
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:    # Port where Zabbix UI is available
      - 80:80
  zabbix-agent:   # Zabbix agent service that tracks usage and send to zabbix server
    image: zabbix/zabbix-agent:latest
    privileged: true   # Access mode for allowing resource access
    network_mode: "host"
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=zabbix-server # The IP/Dns of Zabbix server
  adminer:  # Optional for accessing databases
    image: adminer:latest
    restart: always
    ports:
      - 8090:8080
  grafana-xxl:  # Optional more functional and creative UI 
    image: monitoringartist/grafana-xxl:latest
    ports:
     - 3000:3000
volumes:
  zabbix_pgdata:
